In [6]:
import pandas as pd


baseVendas_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendas_Merge.xlsx")

baseProdutos_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Produtos_Merge.xlsx")

baseVendedores_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendedores_Merge.xlsx")


display(baseVendas_DF)

,Id Vendedor,ID Produto,Data Venda,Quantidade Vendida,Valor Unitário,Total Vendas
0,27264,100482,2023-01-01,8,89.99,719.92
1,21732,100359,2023-01-02,2,69.99,139.98
2,27082,100105,2023-01-03,2,153.40,306.80
3,22936,100212,2023-01-04,10,148.56,1485.60
4,21164,100244,2023-01-05,6,146.14,876.84
5,28824,100301,2023-01-06,2,224.14,448.28
6,27264,100345,2023-01-07,4,150.50,602.00
7,21732,100411,2023-01-08,4,248.73,994.92
8,27082,100128,2023-01-09,9,116.52,1048.68
9,22936,100877,2023-01-10,1,59.90,59.90
10,27264,100208,2023-01-11,6,46.90,281.40
11,21732,100226,2023-01-12,2,41.90,83.80
12,27082,100128,2023-01-13,7,81.90,573.30
13,22936,100443,2023-01-14,9,55.90,503.10
14,21732,100001,2023-01-15,8,89.90,719.20
15,37579,100482,2023-01-16,4,89.99,359.96
16,20437,100359,2023-01-17,7,69.99,489.93
17,21732,100105,2023-01-18,7,153.40,1073.80
18,27082,100212,2023-01-19,7,148.56,1039.92
19,27264,100244,2023-01-20,9,146.14,1315.26
20,28824,100301,2023-01-21,6,224.14,1344.84
21,27264,100345,2023-01-22,6,150.50,903.00
22,21732,100411,2023-01-23,4,248.73,994.92
23,27082,100128,2023-01-24,9,116.52,1048.68
24,22936,100877,2023-01-25,8,59.90,479.20
25,21732,100208,2023-01-26,5,46.90,234.50
26,27082,100226,2023-01-27,9,41.90,377.10
27,22936,100128,2023-01-28,9,81.90,737.10

In [10]:
import pandas as pd


baseVendas_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendas_Merge.xlsx")

baseProdutos_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Produtos_Merge.xlsx")

baseVendedores_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendedores_Merge.xlsx")

#MERGE= Uniu através de um denominador COMUM
baseVendas_DF = baseVendas_DF.merge(baseVendedores_DF)

display(baseVendas_DF)

,Id Vendedor,ID Produto,Data Venda,Quantidade Vendida,Valor Unitário,Total Vendas,Vendedor,Meta
0,27264,100482,2023-01-01,8,89.99,719.92,Leonardo Almeida,5000
1,27264,100345,2023-01-07,4,150.50,602.00,Leonardo Almeida,5000
2,27264,100208,2023-01-11,6,46.90,281.40,Leonardo Almeida,5000
3,27264,100244,2023-01-20,9,146.14,1315.26,Leonardo Almeida,5000
4,27264,100345,2023-01-22,6,150.50,903.00,Leonardo Almeida,5000
5,21732,100359,2023-01-02,2,69.99,139.98,Eliane Moreira,5000
6,21732,100411,2023-01-08,4,248.73,994.92,Eliane Moreira,5000
7,21732,100226,2023-01-12,2,41.90,83.80,Eliane Moreira,5000
8,21732,100001,2023-01-15,8,89.90,719.20,Eliane Moreira,5000
9,21732,100105,2023-01-18,7,153.40,1073.80,Eliane Moreira,5000
10,21732,100411,2023-01-23,4,248.73,994.92,Eliane Moreira,5000
11,21732,100208,2023-01-26,5,46.90,234.50,Eliane Moreira,5000
12,27082,100105,2023-01-03,2,153.40,306.80,Nicolas Pereira,5000
13,27082,100128,2023-01-09,9,116.52,1048.68,Nicolas Pereira,5000
14,27082,100128,2023-01-13,7,81.90,573.30,Nicolas Pereira,5000
15,27082,100212,2023-01-19,7,148.56,1039.92,Nicolas Pereira,5000
16,27082,100128,2023-01-24,9,116.52,1048.68,Nicolas Pereira,5000
17,27082,100226,2023-01-27,9,41.90,377.10,Nicolas Pereira,5000
18,22936,100212,2023-01-04,10,148.56,1485.60,Amanda Martins,5000
19,22936,100877,2023-01-10,1,59.90,59.90,Amanda Martins,5000
20,22936,100443,2023-01-14,9,55.90,503.10,Amanda Martins,5000
21,22936,100877,2023-01-25,8,59.90,479.20,Amanda Martins,5000
22,22936,100128,2023-01-28,9,81.90,737.10,Amanda Martins,5000
23,21164,100244,2023-01-05,6,146.14,876.84,Paulo Santos,5000
24,28824,100301,2023-01-06,2,224.14,448.28,Gabriel Cardoso,5000
25,28824,100301,2023-01-21,6,224.14,1344.84,Gabriel Cardoso,5000
26,37579,100482,2023-01-16,4,89.99,359.96,Angela Maria,5000
27,20437,100359,2023-01-17,7,69.99,489.93,Carlos Moreira,5000

In [9]:
import pandas as pd


baseVendas_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendas_Merge.xlsx")

baseProdutos_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Produtos_Merge.xlsx")

baseVendedores_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendedores_Merge.xlsx")

#MERGE= Uniu através de um denominador COMUM
baseVendas_DF = baseVendas_DF.merge(baseProdutos_DF)

display(baseVendas_DF)

,Id Vendedor,ID Produto,Data Venda,Quantidade Vendida,Valor Unitário,Total Vendas,Produto
0,27264,100482,2023-01-01,8,89.99,719.92,Tênis Feminino
1,37579,100482,2023-01-16,4,89.99,359.96,Tênis Feminino
2,21732,100359,2023-01-02,2,69.99,139.98,Calça Feminina Jogger
3,20437,100359,2023-01-17,7,69.99,489.93,Calça Feminina Jogger
4,27082,100105,2023-01-03,2,153.40,306.80,Camisa Masculina
5,21732,100105,2023-01-18,7,153.40,1073.80,Camisa Masculina
6,22936,100212,2023-01-04,10,148.56,1485.60,Bermuda Masculino
7,27082,100212,2023-01-19,7,148.56,1039.92,Bermuda Masculino
8,21164,100244,2023-01-05,6,146.14,876.84,Camisa Masculina Festa Balada
9,27264,100244,2023-01-20,9,146.14,1315.26,Camisa Masculina Festa Balada
10,28824,100301,2023-01-06,2,224.14,448.28,Bota Masculina
11,28824,100301,2023-01-21,6,224.14,1344.84,Bota Masculina
12,27264,100345,2023-01-07,4,150.50,602.00,Jaqueta Masculina Preta
13,27264,100345,2023-01-22,6,150.50,903.00,Jaqueta Masculina Preta
14,21732,100411,2023-01-08,4,248.73,994.92,Bolsa de Trabalho
15,21732,100411,2023-01-23,4,248.73,994.92,Bolsa de Trabalho
16,27082,100128,2023-01-09,9,116.52,1048.68,Kit de Pinceis de Maquiagem
17,27082,100128,2023-01-24,9,116.52,1048.68,Kit de Pinceis de Maquiagem
18,22936,100877,2023-01-10,1,59.90,59.90,Vestido Infantil
19,22936,100877,2023-01-25,8,59.90,479.20,Vestido Infantil
20,27264,100208,2023-01-11,6,46.90,281.40,Calça Bailarina
21,21732,100208,2023-01-26,5,46.90,234.50,Calça Bailarina
22,21732,100226,2023-01-12,2,41.90,83.80,Camisa Térmica
23,27082,100226,2023-01-27,9,41.90,377.10,Camisa Térmica
24,27082,100128,2023-01-13,7,81.90,573.30,Sapato Social
25,22936,100128,2023-01-28,9,81.90,737.10,Sapato Social
26,22936,100443,2023-01-14,9,55.90,503.10,Sapatilha Sapato
27,21732,100001,2023-01-15,8,89.90,719.20,Colar Pingente

In [11]:
import pandas as pd


baseVendas_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendas_Merge.xlsx")

baseProdutos_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Produtos_Merge.xlsx")

baseVendedores_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendedores_Merge.xlsx")

#MERGE= Uniu através de um denominador COMUM
baseVendas_DF = baseVendas_DF.merge(baseProdutos_DF)

baseVendas_DF = baseVendas_DF.merge(baseVendedores_DF)

display(baseVendas_DF)

,Id Vendedor,ID Produto,Data Venda,Quantidade Vendida,Valor Unitário,Total Vendas,Produto,Vendedor,Meta
0,27264,100482,2023-01-01,8,89.99,719.92,Tênis Feminino,Leonardo Almeida,5000
1,27264,100244,2023-01-20,9,146.14,1315.26,Camisa Masculina Festa Balada,Leonardo Almeida,5000
2,27264,100345,2023-01-07,4,150.50,602.00,Jaqueta Masculina Preta,Leonardo Almeida,5000
3,27264,100345,2023-01-22,6,150.50,903.00,Jaqueta Masculina Preta,Leonardo Almeida,5000
4,27264,100208,2023-01-11,6,46.90,281.40,Calça Bailarina,Leonardo Almeida,5000
5,37579,100482,2023-01-16,4,89.99,359.96,Tênis Feminino,Angela Maria,5000
6,21732,100359,2023-01-02,2,69.99,139.98,Calça Feminina Jogger,Eliane Moreira,5000
7,21732,100105,2023-01-18,7,153.40,1073.80,Camisa Masculina,Eliane Moreira,5000
8,21732,100411,2023-01-08,4,248.73,994.92,Bolsa de Trabalho,Eliane Moreira,5000
9,21732,100411,2023-01-23,4,248.73,994.92,Bolsa de Trabalho,Eliane Moreira,5000
10,21732,100208,2023-01-26,5,46.90,234.50,Calça Bailarina,Eliane Moreira,5000
11,21732,100226,2023-01-12,2,41.90,83.80,Camisa Térmica,Eliane Moreira,5000
12,21732,100001,2023-01-15,8,89.90,719.20,Colar Pingente,Eliane Moreira,5000
13,20437,100359,2023-01-17,7,69.99,489.93,Calça Feminina Jogger,Carlos Moreira,5000
14,27082,100105,2023-01-03,2,153.40,306.80,Camisa Masculina,Nicolas Pereira,5000
15,27082,100212,2023-01-19,7,148.56,1039.92,Bermuda Masculino,Nicolas Pereira,5000
16,27082,100128,2023-01-09,9,116.52,1048.68,Kit de Pinceis de Maquiagem,Nicolas Pereira,5000
17,27082,100128,2023-01-24,9,116.52,1048.68,Kit de Pinceis de Maquiagem,Nicolas Pereira,5000
18,27082,100226,2023-01-27,9,41.90,377.10,Camisa Térmica,Nicolas Pereira,5000
19,27082,100128,2023-01-13,7,81.90,573.30,Sapato Social,Nicolas Pereira,5000
20,22936,100212,2023-01-04,10,148.56,1485.60,Bermuda Masculino,Amanda Martins,5000
21,22936,100877,2023-01-10,1,59.90,59.90,Vestido Infantil,Amanda Martins,5000
22,22936,100877,2023-01-25,8,59.90,479.20,Vestido Infantil,Amanda Martins,5000
23,22936,100128,2023-01-28,9,81.90,737.10,Sapato Social,Amanda Martins,5000
24,22936,100443,2023-01-14,9,55.90,503.10,Sapatilha Sapato,Amanda Martins,5000
25,21164,100244,2023-01-05,6,146.14,876.84,Camisa Masculina Festa Balada,Paulo Santos,5000
26,28824,100301,2023-01-06,2,224.14,448.28,Bota Masculina,Gabriel Cardoso,5000
27,28824,100301,2023-01-21,6,224.14,1344.84,Bota Masculina,Gabriel Cardoso,5000

In [12]:
import pandas as pd


baseVendas_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendas_Merge.xlsx")

baseProdutos_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Produtos_Merge.xlsx")

baseVendedores_DF = pd.read_excel(r"C:\\Users\\thais\\Documents\\Udemy - Curso de Python com RPA e Criação de Projetos Reais\Python e Pandas - Análise e Tratamento de Dados\\Planilhas\\Vendedores_Merge.xlsx")

#MERGE= Uniu através de um denominador COMUM
baseVendas_DF = baseVendas_DF.merge(baseProdutos_DF)

baseVendas_DF = baseVendas_DF.merge(baseVendedores_DF)


resumoDF = baseVendas_DF[["Vendedor","Produto","Total Vendas"]]
display(resumoDF)

            Vendedor                        Produto  Total Vendas
0   Leonardo Almeida                 Tênis Feminino        719.92
1   Leonardo Almeida  Camisa Masculina Festa Balada       1315.26
2   Leonardo Almeida        Jaqueta Masculina Preta        602.00
3   Leonardo Almeida        Jaqueta Masculina Preta        903.00
4   Leonardo Almeida                Calça Bailarina        281.40
5       Angela Maria                 Tênis Feminino        359.96
6     Eliane Moreira          Calça Feminina Jogger        139.98
7     Eliane Moreira               Camisa Masculina       1073.80
8     Eliane Moreira              Bolsa de Trabalho        994.92
9     Eliane Moreira              Bolsa de Trabalho        994.92
10    Eliane Moreira                Calça Bailarina        234.50
11    Eliane Moreira                 Camisa Térmica         83.80
12    Eliane Moreira                 Colar Pingente        719.20
13    Carlos Moreira          Calça Feminina Jogger        489.93
14   Nicolas Pereira               Camisa Masculina        306.80
15   Nicolas Pereira              Bermuda Masculino       1039.92
16   Nicolas Pereira    Kit de Pinceis de Maquiagem       1048.68
17   Nicolas Pereira    Kit de Pinceis de Maquiagem       1048.68
18   Nicolas Pereira                 Camisa Térmica        377.10
19   Nicolas Pereira                  Sapato Social        573.30
20    Amanda Martins              Bermuda Masculino       1485.60
21    Amanda Martins               Vestido Infantil         59.90
22    Amanda Martins               Vestido Infantil        479.20
23    Amanda Martins                  Sapato Social        737.10
24    Amanda Martins               Sapatilha Sapato        503.10
25      Paulo Santos  Camisa Masculina Festa Balada        876.84
26   Gabriel Cardoso                 Bota Masculina        448.28
27   Gabriel Cardoso                 Bota Masculina       1344.84